# Replace
.config/kanshi/config

# Where to put?
.local/share/applications/xeyes.desktop

# Fix secret
.config/tiny/config.yml

# Work
.config/k9s/config.yaml
.config/k9s/skins/catppuccin-mocha.yaml .config/k9s/themes/catppuccin/dist/catppuccin-mocha.yaml
.local/share/applications/google-earth-pro.desktop
.local/share/azure/config
.psqlrc
