idle_bg = "#181825" # mantle
idle_fg = "#cdd6f4" # text

info_bg = "#89b4fa" # blue
info_fg = "#11111b" # crust

good_bg = "#a6e3a1" # green
good_fg = "#11111b" # crust

warning_bg = "#fab387" # peach
warning_fg = "#11111b" # crust

critical_bg = "#f38ba8" # red
critical_fg = "#11111b" # crust

separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
