#!/bin/bash

# Author: Carl Smedstad
# Origin: github.com/carlsmedstad/dotfiles
# Last changed: 2017/10/11


# Replace local files with links to repo
while read -r path; do
  repopath=${path:2}
  localpath=$HOME/$repopath

  if [[ ! $repopath =~ (package-list|dotstrap) ]]; then
    if [ -L $localpath ]; then
      echo "Skipping : $repopath"
    elif [ -z "$(diff $repopath $localpath)" ]; then
      ln -srf $repopath $localpath
      echo "Replaced: $repopath"
    else
      echo "Skipped:  $repopath"
    fi
  fi
done < <(find -type f ! -path *.git/*)

# Copy package list
pacman -Qq > package-list
echo Package list copied
