#!/bin/sh

set -eu

if [ -f /etc/arch-release ]; then
  pacman -Qqen > pkgs/arch.official.txt
  pacman -Qqem > pkgs/arch.aur.txt
elif [ "$(uname)" = Darwin ]; then
  brew bundle dump --force --file pkgs/Brewfile
fi
