#!/bin/sh -eu

command -v paru > /dev/null 2>&1 && exit 0

repo_dir=$(mktemp -d)
old_dir="$(pwd)"
trap 'cd "$old_dir"' EXIT
cd "$repo_dir"

git clone https://aur.archlinux.org/paru-git.git "$repo_dir"
makepkg --noconfirm --syncdeps --rmdeps --install --clean
