#!/bin/sh -eu

screenshot_dir=${SCREENSHOT_DIR:-"$HOME/tmp/screeshots"}

mode=${1:-full}

file_name=$(date +"%Y-%m-%dT%H:%M:%S%:z").png

mkdir -p "$screenshot_dir"

if [ "$mode" = "full" ]; then
  focused_output=$(
    swaymsg -t get_tree \
      | jq -r '
        .nodes[]
        | select([recurse(.nodes[]?, .floating_nodes[]?) | .focused ] | any)
        | .name
      '
  )
  grim -c -o "$focused_output" "$screenshot_dir/$file_name"
fi

if [ "$mode" = "region" ]; then
  slurp | grim -g - "$screenshot_dir/$file_name"
fi
