[theme]
theme = "catppuccin-mocha.toml"

[theme.overrides]
separator = ""

[icons]
icons = "awesome6"

[[block]]
block = "sound"
show_volume_when_muted = true
max_vol = 100
format = "  $icon $volume "

[[block]]
block = "music"
player = "spotify"
format = "{ $play $combo.str(min_w:20, max_w:20, rot_interval:0.5) |}"
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "right"
action = "next"

[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
disconnected_format = ""
format = " $icon "

[[block]]
block = "net"
format = "  $icon  {$signal_strength $ssid|Wired connection} "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
format = " $icon $utilization.eng(w:3) "
interval = 1

[[block]]
block = "battery"
full_format	= " $icon $percentage "
charging_format = " $icon $percentage "
empty_format= " $icon $percentage "

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d %R') "
