[theme]
name = "solarized-dark"
[theme.overrides]
separator = ""

[icons]
name = "awesome5"

[[block]]
block = "sound"
show_volume_when_muted = true
max_vol = 100

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}"

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %F %R"
