servers:
  - addr: irc.libera.chat
    port: 6697
    tls: true
    nicks: [carsme]
    realname: Carl Smedstad

    join:
      - "#archlinux"
      - "#archlinux-aur"
      - "#archlinux-aurweb"
      - "#archlinux-devops"
      - "#archlinux-nordics"
      - "#archlinux-offtopic"
      - "#archlinux-projects"
      - "#archlinux-wiki"
      - "#sway"

    sasl:
      username: "carsme"
      password:
        command: "gpg --decrypt --quiet /home/carsme/.config/tiny/creds/irc.libera.chat.gpg"

defaults:
  nicks: [carsme]
  realname: Carl Smedstad
  join: []
  tls: true

log_dir: "/home/carsme/.local/state/tiny_logs"

colors:
  nick: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14]

  clear:
    fg: default
    bg: default

  user_msg:
    fg: black
    bg: default

  err_msg:
    fg: black
    bg: maroon
    attrs: [bold]

  topic:
    fg: cyan
    bg: default
    attrs: [bold]

  cursor:
    fg: black
    bg: default

  join:
    fg: lime
    bg: default
    attrs: [bold]

  part:
    fg: maroon
    bg: default
    attrs: [bold]

  nick_change:
    fg: lime
    bg: default
    attrs: [bold]

  faded:
    fg: 242
    bg: default

  exit_dialogue:
    fg: 27
    bg: red

  highlight:
    fg: red
    bg: default
    attrs: [bold]

  completion:
    fg: 84
    bg: default

  timestamp:
    fg: 242
    bg: default

  tab_active:
    fg: default
    bg: default
    attrs: [bold]

  tab_normal:
    fg: gray
    bg: default

  tab_new_msg:
    fg: purple
    bg: default

  tab_highlight:
    fg: red
    bg: default
    attrs: [bold]
