#!/bin/sh -eu

_install() {
  install -D --mode "$1" --compare "$2" "/$2"
}

_install 644 etc/bluetooth/main.conf
_install 644 etc/greetd/config.toml
_install 644 etc/modules-load.d/btusb.conf
_install 644 etc/systemd/journald.conf
_install 644 etc/tlp.d/10-disable-usb-autosuspend.conf
_install 644 etc/udev/rules.d/backlight.rules
_install 644 etc/xdg/reflector/reflector.conf
_install 644 usr/local/lib/wayland-enablement.sh

_install 755 usr/local/bin/sway-run
