name: lint
on: [push]

jobs:
  shell:
    runs-on: ubuntu-latest
    container: alpine:3
    steps:
      - uses: actions/checkout@v2
      - run: |
          apk add make
          apk add shfmt
          apk add shellcheck
      - run: make check-shellcheck
      - run: make check-shfmt
  lua:
    runs-on: ubuntu-latest
    env:
      STYLUA_VERSION: "0.13.1"
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -LO https://github.com/JohnnyMorganz/StyLua/releases/download/v$STYLUA_VERSION/stylua-linux.zip
          unzip stylua-linux.zip -d /usr/local/bin/
          chmod u+x /usr/local/bin/stylua
      - run: make check-stylua
