name: lint
on: [push]

jobs:
  shell:
    runs-on: ubuntu-latest
    container: alpine:3
    steps:
      - uses: actions/checkout@v2
      - run: apk add make
      - run: apk add shfmt
      - run: apk add shellcheck
      - run: make check-shellcheck
      - run: make check-shfmt
  lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
