name: lint
on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable
    steps:
      - uses: actions/checkout@v2
      - run: apk add make
      - run: make shellcheck
